In [2]:
import torch


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7537, 0.8008, 0.9935],
        [0.5067, 0.8717, 0.5022],
        [0.3093, 0.1406, 0.9802],
        [0.3424, 0.6576, 0.1276],
        [0.1249, 0.4605, 0.4466]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)   

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.4917,  1.3522, -0.3073],
        [-0.0382, -0.6765,  0.0099],
        [ 1.5231,  0.9880, -0.6200],
        [ 1.6306, -0.1453,  0.6589],
        [-0.3297,  1.1499,  0.0923]])


In [6]:
torch.Size([5, 3])

torch.Size([5, 3])

In [7]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.7412,  1.7342,  0.1758],
        [ 0.2826,  0.3052,  0.6824],
        [ 1.8426,  1.0809, -0.5973],
        [ 2.5445,  0.8540,  0.9591],
        [ 0.5706,  1.9782,  0.7563]])


In [8]:
print(torch.add(x, y))

tensor([[ 1.7412,  1.7342,  0.1758],
        [ 0.2826,  0.3052,  0.6824],
        [ 1.8426,  1.0809, -0.5973],
        [ 2.5445,  0.8540,  0.9591],
        [ 0.5706,  1.9782,  0.7563]])


In [9]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.7412,  1.7342,  0.1758],
        [ 0.2826,  0.3052,  0.6824],
        [ 1.8426,  1.0809, -0.5973],
        [ 2.5445,  0.8540,  0.9591],
        [ 0.5706,  1.9782,  0.7563]])


In [10]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.7412,  1.7342,  0.1758],
        [ 0.2826,  0.3052,  0.6824],
        [ 1.8426,  1.0809, -0.5973],
        [ 2.5445,  0.8540,  0.9591],
        [ 0.5706,  1.9782,  0.7563]])


In [11]:
print(x[:, 1])

tensor([ 1.3522, -0.6765,  0.9880, -0.1453,  1.1499])


In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [13]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.6679])
0.6679013967514038


In [14]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [15]:
print(y.grad_fn)


None


In [16]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [17]:
y = x + 2
print(y)a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [18]:
print(y.grad_fn)

In [19]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [20]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [21]:
out.backward()

In [22]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [23]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
